[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
name = "pdb-downloader"
version = "0.1.0"
edition = "2018"

[dependencies]
goblin = "~0.3"
indicatif = "~0.15"
reqwest = "~0.11"
thiserror = "~1.0"
tokio = { version = "1", features = ["full"] }

[profile.release]
panic = "abort"
